### PR TITLE
Observe DefinitelyTyped protocol for major-version updates

### PR DESCRIPTION
**Pull request by smhxx**
Per the DefinitelyTyped [protocol for major-version updates](https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-update-a-package-to-a-new-major-version), this PR archives the previous versions of each package being updated in a versioned sub-directory, and links their dependencies to the outdated version's new location.

This is super-straightforward, doesn't mess with any of the new code, and should speed along the process of getting merged upstream once everything's ready for the final PR. 😄

### CODE REVIEW

**Comment by smhxx** [comment]
Okay, hold on. It's yelling at me about stuff that I didn't think it would. Give me a second to fix the build. lol

**Comment by smhxx** [comment]
Alright, I'm at a loss here. For some bizarre reason, the compiler is just completely ignoring the `tsconfig` settings and resolving the *new* versions of modules instead of the old ones... which of course is throwing a ton of compiler errors. I've been poking at this for a while and whatever is causing this seems to defy all logic and all understanding that I have of TypeScript. rofl

At this point I'm 100% certain that either: it's something totally obvious and I'm just an idiot; or, it's some sort of weird bug that somehow nobody has noticed yet. Probably the first. I've got one more thing I want to check, and if I can't figure it out, I may drop by the DT gitter for feedback.

**Comment by smhxx** [comment]
Eyy! There we go! Took me a while, but I finally figured out how to untangle the mess of inter-dependencies and get all the outdated versions referencing each other correctly. Might be pointless, since I doubt anyone was still using that old stuff, but at least now the DT people shouldn't have a problem with the outdated defs being replaced.

**Comment by GlenCFL** [comment]
It's a good precedence to set going forward anyway. Thanks for taking the time to figure it out.

I'm going to be writing the syntax tests for every public API class throughout today, then hopefully I'll have time to resolve some other issues.

**Comment by GlenCFL** [comment]
Forgot to remove the # reference, so I've amended that commit.

**Pull request merged**
